---
name: Release

on:
  pull_request:
    branches: ["main"]
    paths: ["charts/**/metadata.yaml"]
  push:
    branches: ["main"]
    paths: ["charts/**/metadata.yaml"]
  workflow_dispatch:
    inputs:
      chart:
        description: Chart to release
        required: true

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  changed-files:
    name: Get Changed Files
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.charts.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - if: ${{ github.event_name != 'workflow_dispatch' }}
        name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: charts/**/metadata.yaml

      - name: Extract Chart values
        id: charts
        run: |
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]]; then
            charts="${{ steps.changed-files.outputs.all_changed_and_modified_files }}"
          else
            charts="charts/${{ inputs.chart }}/metadata.yaml"
          fi
          charts=$(yq eval-all --indent=0 --output-format=json "[.]" $charts)
          echo "charts=${charts}" >> $GITHUB_OUTPUT

  push-charts:
    needs: changed-files
    name: Push Charts
    runs-on: ubuntu-latest
    if: ${{ needs.changed-files.outputs.charts != '[]' }}
    strategy:
      matrix:
        charts: ${{ fromJSON(needs.changed-files.outputs.charts) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4

      - if: ${{ github.event_name != 'pull_request' }}
        name: Install Cosign
        uses: sigstore/cosign-installer@398d4b0eeef1380460a10c8013a76f728fb906ac # v3

      - if: ${{ github.event_name != 'pull_request' }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Add Helm Repository
        run: helm repo add upstream ${{ matrix.charts.registry }}

      - name: Update Helm Repository
        run: helm repo update upstream

      - name: Pull Chart
        run: helm pull upstream/${{ matrix.charts.chart }} --version ${{ matrix.charts.version }}

      - name: Set lowercase repository name
        id: lowercase
        run: |
          echo "repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - if: ${{ github.event_name != 'pull_request' }}
        name: Push Chart
        run: helm push *.tgz oci://ghcr.io/${{ steps.lowercase.outputs.repo }}

      - if: ${{ github.event_name != 'pull_request' }}
        name: Sign artifacts with Cosign
        run: cosign sign --yes ghcr.io/${{ steps.lowercase.outputs.repo }}/${{ matrix.charts.chart }}:${{ matrix.charts.version }}
